#!/bin/bash

termux-setup-storage

apt update
apt upgrade

pkg install ncurses-utils

pkg install python
pip install youtube-dl

mkdir ~/bin

cp ~/termux-youtube-downloader/termux-url-opener ~/bin/


