#!/bin/bash

echo  "----------------------------"
figlet Viliyam && figlet Vasava

echo  "----------------------------\n"

echo  "How to Dowload Youtube Videos?\n"

echo  " - Open Youtube Aap.\n"

echo  " - Select the Video you want to Dowlload.\n"

echo  " - Click on Share Button.\n"

echo  " - Then Select Termux.\n"

echo  " - Select Your Download Format.\n"

echo  " - Enjaoy....\n"




